name: dart_geohash
version: 2.0.2
description: A simple encode, decode, and neighbor finder for longitude/latitude and geohash.
homepage: https://github.com/nfrawley93/dart_geohash
repository: https://github.com/nfrawley93/dart_geohash

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  test: ^1.20.1
